name: 'Renovate Merge'
author: 'MansaGroup'
description: "Merge any Renovate's ready pull request but blocked by the CODEOWNERS"
branding:
  icon: 'git-merge'
  color: 'blue'
inputs:
  githubToken:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
